const fallback={contributions:646,repositories:16,merged_prs:50,open_prs:24,stars:0,weekly:[],languages:{TypeScript:5,JavaScript:4,Python:3,HTML:2,PHP:1}};let data=fallback,range=52,hover=-1;
const projects=[['TPO','Multi-role placement platform with secure workflows and production deployment.'],['KETPORT','React and TypeScript portfolio system with deliberate motion and delivery automation.'],['Chikitsamedha','Privacy-first medicine safety analysis with explainable risk scoring.'],['Plant-Disease-Recognition-System','PyTorch computer vision with bilingual, offline-ready operator workflows.']];
const capabilities={AI:'LLMs, retrieval, computer vision, evaluation systems.',Backend:'Python, Django, FastAPI, async workflows, REST.',Cloud:'Cloudflare, AWS, containers, observability, delivery.',Security:'Network defense, authorization boundaries, risk analysis.',Product:'React, TypeScript, accessible decision-focused UX.'};
const $=s=>document.querySelector(s);const metrics=()=>$('#metrics').innerHTML=[['CONTRIBUTIONS / 12M',data.contributions],['PUBLIC REPOSITORIES',data.repositories],['MERGED PULL REQUESTS',data.merged_prs],['OPEN PULL REQUESTS',data.open_prs]].map(x=>`<article class="metric"><span>${x[0]}</span><b>${x[1]}</b></article>`).join('');
function languages(){let entries=Object.entries(data.languages),sum=entries.reduce((a,[,v])=>a+v,0)||1;$('#languages').innerHTML=entries.slice(0,6).map(([k,v])=>`<div class="lang-row"><span>${k}</span><div class="bar"><i style="width:${v/sum*100}%"></i></div><b>${(v/sum*100).toFixed(1)}%</b></div>`).join('')}
function draw(){let c=$('#velocity'),dpr=devicePixelRatio||1,r=c.getBoundingClientRect();c.width=r.width*dpr;c.height=r.height*dpr;let x=c.getContext('2d');x.scale(dpr,dpr);let vals=(data.weekly||[]).slice(-range);if(!vals.length)vals=Array.from({length:range},(_,i)=>Math.max(0,Math.round(Math.sin(i*.45)*4+i/range*5)));let pad=30,w=r.width-pad*2,h=r.height-pad*2,max=Math.max(...vals,1);x.strokeStyle='#1e293b';x.lineWidth=1;for(let i=0;i<5;i++){let y=pad+i*h/4;x.beginPath();x.moveTo(pad,y);x.lineTo(r.width-pad,y);x.stroke()}let pts=vals.map((v,i)=>[pad+i*w/(vals.length-1),r.height-pad-v/max*h]);let g=x.createLinearGradient(0,pad,0,r.height-pad);g.addColorStop(0,'#2563eb66');g.addColorStop(1,'#2563eb00');x.beginPath();x.moveTo(pts[0][0],r.height-pad);pts.forEach(p=>x.lineTo(...p));x.lineTo(pts.at(-1)[0],r.height-pad);x.fillStyle=g;x.fill();x.beginPath();pts.forEach((p,i)=>i?x.lineTo(...p):x.moveTo(...p));x.strokeStyle='#38bdf8';x.lineWidth=3;x.shadowColor='#38bdf8';x.shadowBlur=12;x.stroke();if(hover>=0){let p=pts[Math.min(hover,pts.length-1)];x.beginPath();x.arc(...p,6,0,Math.PI*2);x.fillStyle='#f59e0b';x.fill()}c._vals=vals;c._pts=pts}
function inspect(e){let c=$('#velocity'),r=c.getBoundingClientRect(),clientX=e.touches?.[0]?.clientX??e.clientX,i=Math.round((clientX-r.left-30)/(r.width-60)*(c._vals.length-1));hover=Math.max(0,Math.min(c._vals.length-1,i));draw();let p=c._pts[hover],t=$('#tooltip');t.style.display='block';t.style.left=p[0]+'px';t.style.top=p[1]+'px';t.textContent=`WEEK ${hover+1} / ${c._vals[hover]} CONTRIBUTIONS`}
function projectGrid(q=''){q=q.toLowerCase();$('#project-grid').innerHTML=projects.filter(p=>p.join(' ').toLowerCase().includes(q)).map(p=>`<a class="project" href="https://github.com/ketpatil77/${p[0]}"><strong>${p[0]}</strong><p>${p[1]}</p></a>`).join('')}
async function init(){try{let r=await fetch('../assets/telemetry.json',{cache:'no-store'});if(r.ok)data=await r.json()}catch{}metrics();languages();projectGrid();draw();document.querySelectorAll('[data-range]').forEach(b=>b.onclick=()=>{range=+b.dataset.range;document.querySelectorAll('[data-range]').forEach(x=>x.classList.toggle('active',x===b));hover=-1;draw()});let c=$('#velocity');['pointerdown','pointermove'].forEach(ev=>c.addEventListener(ev,e=>{if(ev==='pointerdown'||e.buttons)inspect(e)}));c.onkeydown=e=>{if(['ArrowLeft','ArrowRight'].includes(e.key)){hover=Math.max(0,Math.min((c._vals?.length||1)-1,hover+(e.key==='ArrowRight'?1:-1)));let fake={clientX:c.getBoundingClientRect().left+30+hover*(c.getBoundingClientRect().width-60)/(c._vals.length-1)};inspect(fake)}};document.querySelectorAll('[data-node]').forEach(b=>b.onclick=()=>$('#node-detail').textContent=capabilities[b.dataset.node]);$('#search').oninput=e=>projectGrid(e.target.value);addEventListener('resize',draw,{passive:true})}init();
